import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, CreditCard, QrCode, Smartphone, Loader2, CheckCircle2, AlertTriangle, Download, ShieldCheck } from 'lucide-react'
import { paymentAPI } from '../../services/api'
import toast from 'react-hot-toast'

export default function CheckoutModal({ isOpen, onClose, jobId, applicationId, freelancerId, amount, jobTitle, onSuccess }) {
  const [step, setStep] = useState('select') // select, details, processing, success, fail
  const [paymentMethod, setPaymentMethod] = useState('card') // card, upi, qr
  const [loading, setLoading] = useState(false)
  const [txDetails, setTxDetails] = useState(null)
  
  // Form states
  const [cardData, setCardData] = useState({ number: '', name: '', expiry: '', cvv: '' })
  const [upiId, setUpiId] = useState('')
  const [qrCounter, setQrCounter] = useState(30)

  // QR Code timer simulation
  useEffect(() => {
    let timer
    if (step === 'details' && paymentMethod === 'qr' && qrCounter > 0) {
      timer = setInterval(() => setQrCounter(prev => prev - 1), 1000)
    } else if (qrCounter === 0) {
      setStep('fail')
    }
    return () => clearInterval(timer)
  }, [step, paymentMethod, qrCounter])

  if (!isOpen) return null

  const handleCardChange = (e) => {
    setCardData({ ...cardData, [e.target.name]: e.target.value })
  }

  // 1. Initiate Session on Backend
  const handleInitiate = async () => {
    try {
      setLoading(true)
      const res = await paymentAPI.initiate({
        jobId,
        freelancerId,
        amount,
        applicationId
      })
      if (res.success) {
        setTxDetails({ escrowId: res.escrowId })
        setStep('details')
      }
    } catch (err) {
      toast.error(err.message || 'Failed to initialize payment')
    } finally {
      setLoading(false)
    }
  }

  // 2. Simulate payment submission and verify on Backend
  const handlePay = async (simulateSuccess = true) => {
    if (paymentMethod === 'card' && (!cardData.number || !cardData.cvv || !cardData.name)) {
      return toast.error('Please fill in card details')
    }
    if (paymentMethod === 'upi' && !upiId.includes('@')) {
      return toast.error('Please enter a valid UPI ID')
    }

    try {
      setStep('processing')
      
      // Simulate gateway delay
      await new Promise(resolve => setTimeout(resolve, 2500))

      const res = await paymentAPI.verify({
        escrowId: txDetails.escrowId,
        paymentMethod,
        status: simulateSuccess ? 'success' : 'failed'
      })

      if (res.success) {
        setTxDetails(res.transaction)
        setStep('success')
        if (onSuccess) onSuccess()
      } else {
        setStep('fail')
      }
    } catch (err) {
      setStep('fail')
    }
  }

  // Receipt Download Helper
  const downloadReceipt = () => {
    if (!txDetails) return
    const receiptText = `
==================================================
           WORKLANCE TRANSACTION RECEIPT
==================================================
Receipt ID       : ${txDetails.transactionId}
Payment Gateway  : Cashfree (Simulated Sandbox)
Date/Time        : ${new Date(txDetails.createdAt).toLocaleString()}
Status           : SUCCESSFUL
--------------------------------------------------
Project Title    : ${jobTitle}
Total Amount     : $${amount.toFixed(2)}
Payment Method   : ${paymentMethod.toUpperCase()}
Secure Escrow    : SECURED IN WALLET
--------------------------------------------------
This is a secure electronic receipt generated by
WorkLance Escrow Services.
==================================================
`;
    const blob = new Blob([receiptText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `WorkLance_Receipt_${txDetails.transactionId}.txt`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success('Receipt invoice downloaded!')
  }

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"
        />

        {/* Dialog Content */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="relative w-full max-w-md bg-[var(--sidebar-bg)] border border-[var(--border-color)] rounded-2xl shadow-2xl overflow-hidden text-[var(--text-color)] z-10"
        >
          {/* Header */}
          <div className="p-4 border-b border-[var(--border-color)] flex items-center justify-between">
            <div className="flex items-center gap-1.5">
              <ShieldCheck size={18} className="text-brand-500 animate-pulse" />
              <span className="font-semibold text-sm">Secure Payment Gateway</span>
            </div>
            <button onClick={onClose} className="p-1 rounded-lg hover:bg-brand-500/10 text-[var(--text-color)]/60 hover:text-[var(--text-color)]">
              <X size={18} />
            </button>
          </div>

          <div className="p-6">
            {/* STEP 1: Select payment options */}
            {step === 'select' && (
              <div className="space-y-4">
                <div className="text-center mb-6">
                  <span className="text-xs font-semibold text-brand-600 dark:text-brand-400 tracking-wider uppercase">Funding Amount</span>
                  <h2 className="text-3xl font-display font-bold text-[var(--text-color)] mt-1">${amount.toFixed(2)}</h2>
                  <p className="text-xs text-[var(--text-color)]/60 mt-1 max-w-[250px] mx-auto truncate" title={jobTitle}>{jobTitle}</p>
                </div>

                <div className="glass p-4 rounded-xl space-y-3">
                  <div className="flex items-center gap-3">
                    <div className="w-5 h-5 rounded-full bg-brand-500/20 flex items-center justify-center text-xs font-bold text-brand-500">1</div>
                    <p className="text-xs text-[var(--text-color)]/70">Funds will be safely locked in Escrow.</p>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="w-5 h-5 rounded-full bg-brand-500/20 flex items-center justify-center text-xs font-bold text-brand-500">2</div>
                    <p className="text-xs text-[var(--text-color)]/70">Only release payment when you approve completed work.</p>
                  </div>
                </div>

                <button
                  onClick={handleInitiate}
                  disabled={loading}
                  className="w-full btn-primary flex items-center justify-center gap-2 mt-4"
                >
                  {loading ? <Loader2 size={16} className="animate-spin" /> : 'Select Payment Method'}
                </button>
              </div>
            )}

            {/* STEP 2: Fill Details for Specific Option */}
            {step === 'details' && (
              <div className="space-y-5">
                {/* Mode Selectors */}
                <div className="flex gap-2">
                  {[
                    { id: 'card', label: 'Card', icon: CreditCard },
                    { id: 'upi', label: 'UPI ID', icon: Smartphone },
                    { id: 'qr', label: 'QR Scan', icon: QrCode }
                  ].map((m) => (
                    <button
                      key={m.id}
                      onClick={() => setPaymentMethod(m.id)}
                      className={`flex-1 py-2.5 px-2 rounded-xl border flex flex-col items-center justify-center gap-1.5 text-xs font-semibold transition-all ${
                        paymentMethod === m.id
                          ? 'border-brand-500 bg-brand-500/10 text-brand-600 dark:text-brand-400'
                          : 'border-[var(--border-color)] bg-[var(--card-bg-start)] text-[var(--text-color)]/60 hover:text-[var(--text-color)]'
                      }`}
                    >
                      <m.icon size={16} />
                      {m.label}
                    </button>
                  ))}
                </div>

                {/* Subforms */}
                {paymentMethod === 'card' && (
                  <div className="space-y-3">
                    <div className="space-y-1">
                      <label className="text-[10px] font-semibold uppercase text-[var(--text-color)]/60">Card Number</label>
                      <input
                        type="text"
                        name="number"
                        placeholder="4111 2222 3333 4444"
                        value={cardData.number}
                        onChange={handleCardChange}
                        maxLength={19}
                        className="input-field text-sm"
                      />
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="space-y-1">
                        <label className="text-[10px] font-semibold uppercase text-[var(--text-color)]/60">Expiry Date</label>
                        <input
                          type="text"
                          name="expiry"
                          placeholder="MM/YY"
                          value={cardData.expiry}
                          onChange={handleCardChange}
                          maxLength={5}
                          className="input-field text-sm"
                        />
                      </div>
                      <div className="space-y-1">
                        <label className="text-[10px] font-semibold uppercase text-[var(--text-color)]/60">CVV</label>
                        <input
                          type="password"
                          name="cvv"
                          placeholder="***"
                          value={cardData.cvv}
                          onChange={handleCardChange}
                          maxLength={3}
                          className="input-field text-sm"
                        />
                      </div>
                    </div>
                    <div className="space-y-1">
                      <label className="text-[10px] font-semibold uppercase text-[var(--text-color)]/60">Cardholder Name</label>
                      <input
                        type="text"
                        name="name"
                        placeholder="John Doe"
                        value={cardData.name}
                        onChange={handleCardChange}
                        className="input-field text-sm"
                      />
                    </div>
                  </div>
                )}

                {paymentMethod === 'upi' && (
                  <div className="space-y-3">
                    <div className="space-y-1">
                      <label className="text-[10px] font-semibold uppercase text-[var(--text-color)]/60">Enter UPI ID</label>
                      <input
                        type="text"
                        placeholder="username@okaxis"
                        value={upiId}
                        onChange={(e) => setUpiId(e.target.value)}
                        className="input-field text-sm"
                      />
                    </div>
                    <p className="text-[11px] text-[var(--text-color)]/40">Enter your UPI VPA to receive a mock collect notification.</p>
                  </div>
                )}

                {paymentMethod === 'qr' && (
                  <div className="flex flex-col items-center justify-center p-2 bg-white rounded-2xl border border-slate-200">
                    <img
                      src={`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(
                        `upi://pay?pa=worklance@okaxis&pn=WorkLance&am=${amount}&tr=WL-${txDetails?.escrowId}`
                      )}&color=0f172a`}
                      alt="Mock Payment QR"
                      className="w-40 h-40 object-contain"
                    />
                    <div className="text-center mt-2.5">
                      <p className="text-[11px] font-bold text-slate-800">Scan QR via any UPI App</p>
                      <p className="text-[10px] text-red-500 font-semibold mt-0.5">Expires in: {qrCounter} seconds</p>
                    </div>
                  </div>
                )}

                {/* Simulated Verify buttons */}
                <div className="flex gap-2.5 pt-2">
                  <button
                    onClick={() => handlePay(false)}
                    className="flex-1 px-4 py-2.5 rounded-xl border border-red-500/20 bg-red-500/5 text-red-500 text-xs font-semibold hover:bg-red-500/10 transition-all"
                  >
                    Simulate Fail
                  </button>
                  <button
                    onClick={() => handlePay(true)}
                    className="flex-[2] btn-primary text-xs py-2.5 flex items-center justify-center gap-1.5"
                  >
                    Simulate Success
                  </button>
                </div>
              </div>
            )}

            {/* STEP 3: Processing loading */}
            {step === 'processing' && (
              <div className="flex flex-col items-center justify-center py-12 space-y-4">
                <Loader2 size={48} className="animate-spin text-brand-500" />
                <div className="text-center space-y-1.5">
                  <p className="font-semibold text-sm">Processing Payment...</p>
                  <p className="text-xs text-[var(--text-color)]/40">Securing your connection with Cashfree servers.</p>
                </div>
              </div>
            )}

            {/* STEP 4: Success confirmation screen */}
            {step === 'success' && (
              <div className="text-center py-4 space-y-5">
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  className="w-16 h-16 rounded-full bg-emerald-500/10 text-emerald-500 flex items-center justify-center mx-auto"
                >
                  <CheckCircle2 size={36} />
                </motion.div>
                
                <div className="space-y-1.5">
                  <h3 className="text-lg font-bold text-emerald-500">Payment Successful!</h3>
                  <p className="text-xs text-[var(--text-color)]/50">Funds are secured safely inside the Escrow wallet.</p>
                </div>

                {txDetails && (
                  <div className="glass p-4 rounded-xl text-left text-xs space-y-2 max-w-sm mx-auto border-[var(--border-color)]">
                    <div className="flex justify-between"><span className="opacity-50">Transaction ID</span><span className="font-mono font-semibold">{txDetails.transactionId}</span></div>
                    <div className="flex justify-between"><span className="opacity-50">Payment Mode</span><span className="capitalize">{paymentMethod}</span></div>
                    <div className="flex justify-between"><span className="opacity-50">Amount Funded</span><span className="font-bold">${amount.toFixed(2)}</span></div>
                  </div>
                )}

                <div className="flex gap-2">
                  <button
                    onClick={downloadReceipt}
                    className="flex-1 btn-secondary text-xs py-2.5 flex items-center justify-center gap-1.5"
                  >
                    <Download size={14} /> Receipt
                  </button>
                  <button
                    onClick={onClose}
                    className="flex-1 btn-primary text-xs py-2.5"
                  >
                    Go To Escrow
                  </button>
                </div>
              </div>
            )}

            {/* STEP 5: Failed screen */}
            {step === 'fail' && (
              <div className="text-center py-6 space-y-5">
                <div className="w-16 h-16 rounded-full bg-red-500/10 text-red-500 flex items-center justify-center mx-auto">
                  <AlertTriangle size={36} />
                </div>

                <div className="space-y-1.5">
                  <h3 className="text-lg font-bold text-red-500">Transaction Failed</h3>
                  <p className="text-xs text-[var(--text-color)]/50">The simulated payment was rejected by the sandbox gateway.</p>
                </div>

                <div className="flex gap-2 max-w-xs mx-auto">
                  <button
                    onClick={() => setStep('details')}
                    className="flex-1 btn-secondary text-xs py-2.5"
                  >
                    Try Again
                  </button>
                  <button
                    onClick={onClose}
                    className="flex-1 btn-primary text-xs py-2.5"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            )}
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  )
}
